### ISSUE TITLE
Missing versions

### ISSUE THREAD

**Issue by gcangussu** [jahed/node-terraform#17]
First of all, thanks for the work you've provided so far.

I would like to know if this project could provide newer versions of terraform, which is currently at version 1.9.1 as of this writing. It seems this project stopped providing newer versions after version 1.8.1.

Please let me know if I could help with anything to get newer versions published.

**Comment by jahed** [comment]
Looks like tests are failing. v1.8.2 introduced an additional file in the ZIP download so this project likely needs to change some logic around it. https://github.com/hashicorp/terraform/releases/tag/v1.8.2

**Comment by jahed** [comment]
Fixed for v1.8.2 onwards.

https://github.com/jahed/node-terraform/compare/v1.8.1...v1.8.2#diff-8ec556321f729e1f6c1d49d74cdb7f67f8bc8ad674ba10685ff45d0d8fab7c9d

I've published the backlog of v1.8.2, v1.8.3, v1.8.4, v1.8.5, v1.9.0, v1.9.1.

As usual again, future releases will be automatically checked for and released daily.

Thanks for reporting this issue.
